import { NodeInit, HTMLDOMAssembler } from 'htmlmodule'

const { prototype : { reduce } } = Array
const ARIA_PREFIX = 'aria-'
const ARIA_PREFIX_LENGTH = ARIA_PREFIX.length

export class ARIADOMAssembler extends HTMLDOMAssembler {
    constructor(object, init) {
        super()
        if(typeof object === 'string') this.assemble(object, init)
        else if(object instanceof Node) {
            this.node = object
            if(init) this.init(init)
        }
        if(this.node) this.node.assembler = this
    }

    set role(role) {
        this.node.setAttribute('role', role)
    }

    get role() {
        return this.node.getAttribute('role') || ''
    }

    set aria(aria) {
        const node = this.node
        for(let name in aria) {
            const value = aria[name]
            if(typeof value === 'string') {
                node.setAttribute(ARIA_PREFIX + name, value)
            }
        }
    }

    get aria() {
        return reduce.call(this.node.attributes, (res, { name, value }) => {
            if(name.startsWith(ARIA_PREFIX)) {
                res[name.slice(ARIA_PREFIX_LENGTH)] = value
            }
            return res
        }, {})
    }

    /**
     * [HTML : the id attribute](https://www.w3.org/TR/html5/dom.html#the-id-attribute)
     *
     * Specifies element's [unique identifier (ID)](https://www.w3.org/TR/dom/#concept-id).
     *
     * The value must be unique amongst all the IDs in the element's home subtree and must contain
     * at least one character. The value must not contain any space characters.
     * @param {String} id unique identifier of the element
     */
    set id(id) {
        this.node.id = id
    }

    /**
     * Identifiers are opaque strings. Particular meanings should not be derived from the value of the id attribute.
     *
     * @returns {String} unique identifier, autogenerated if need
     */
    get id() {
        return this.node.id || (this.id = this.constructor.uniqid)
    }

    init(init) {
        super.init(NodeInit(init))
    }

    /**
     * Generate unique identifier
     * @returns {String} unique id
     */
    static get uniqid() {
        let id
        do id = this.name + Math.floor(Math.random() * 1e10)
        while(document.getElementById(id))
        return id
    }
}
